version: '2'
services:

  api:
    image: backend490
    ports:
      - "5000:5000"
    environment:
      - LANG=${LANG}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  data:
    restart: always
    image: mysql:5.6
    volumes:
      - /var/lib/mysql
    command: "true"

  db:
    restart: always
    image: mysql:5.6
    volumes:
      - ./mysql_conf:/etc/mysql/conf.d
    volumes_from:
      - data
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    tty: true
